
POST https://awacademy-kleinanzeigen.azurewebsites.net/user/login
//user/login

###

GET https://awacademy-kleinanzeigen.azurewebsites.net/user/me
//user/me
###

POST https://awacademy-kleinanzeigen.azurewebsites.net/user/register
//register

###
GET https://awacademy-kleinanzeigen.azurewebsites.net/user/1
//user/id
###